/**
 * Cycle Reporter — generates hourly performance reports.
 *
 * After each 50-min cycle, produces a structured report with:
 *   - PnL summary per strategy
 *   - Win/loss breakdown by confidence bucket
 *   - Fee analysis (how much edge was eaten by fees)
 *   - Market regime detection (trending vs sideways)
 *   - Specific improvement recommendations
 *
 * Reports are stored in BotLog for historical reference.
 */

import 'server-only';

import { prisma } from '@/lib/db/prisma';
import {
  getTradeStats,
  getConfidenceBuckets,
  getRecentTrades,
  type TradeStats,
  type TradeLogEntry,
  type TradeStrategy,
} from './trade-logger';

// ─── Report Types ──────────────────────────────────────

export interface CycleReport {
  cycleNumber: number;
  startTime: string;
  endTime: string;
  durationMinutes: number;

  // Overall
  totalTrades: number;
  totalPnl: number;
  balanceBefore: number;
  balanceAfter: number;
  roi: number; // % return on balance

  // Per strategy
  strategies: {
    'latency-arb': StrategyReport;
    'expiry-sniper': StrategyReport;
  };

  // Diagnostics
  signalsGenerated: number;
  signalsSkipped: number;
  ordersPlaced: number;
  ordersFailed: number;

  // Fee analysis
  totalFeePaid: number;
  avgFeePct: number;
  feeAsEdgePct: number; // what % of raw edge was eaten by fees

  // Market conditions
  marketRegime: 'trending' | 'sideways' | 'volatile' | 'unknown';
  priceRange: { asset: string; low: number; high: number; changePct: number }[];

  // Improvement suggestions (generated by analyzeAndSuggest)
  improvements: Improvement[];
}

export interface StrategyReport {
  stats: TradeStats;
  confidenceBuckets: { bucket: string; trades: number; winRate: number; avgPnl: number }[];
  bestTrade: TradeSummary | null;
  worstTrade: TradeSummary | null;
}

export interface TradeSummary {
  conditionId: string;
  direction: string;
  entryPrice: number;
  pnl: number;
  confidence: number;
  edge: number;
}

export interface Improvement {
  area: 'confidence' | 'edge' | 'sizing' | 'fees' | 'timing' | 'strategy' | 'risk';
  severity: 'critical' | 'warning' | 'info';
  message: string;
  /** Concrete parameter change suggestion */
  suggestion?: { param: string; from: number; to: number };
}

// ─── Report Generation ────────────────────────────────

export async function generateCycleReport(
  profileId: string,
  cycleNumber: number,
  startTime: Date,
  endTime: Date,
  balanceBefore: number,
  balanceAfter: number,
): Promise<CycleReport> {
  const durationMinutes = (endTime.getTime() - startTime.getTime()) / 60_000;
  const hoursBack = durationMinutes / 60;

  // Get stats for both strategies
  const [arbStats, sniperStats] = await Promise.all([
    getTradeStats(profileId, 'latency-arb', hoursBack),
    getTradeStats(profileId, 'expiry-sniper', hoursBack),
  ]);

  const [arbBuckets, sniperBuckets] = await Promise.all([
    getConfidenceBuckets(profileId, 'latency-arb', hoursBack),
    getConfidenceBuckets(profileId, 'expiry-sniper', hoursBack),
  ]);

  // Get all trades in this window
  const allTrades = await getRecentTrades(profileId, undefined, 200);
  const cycleTrades = allTrades.filter(t =>
    t.signalTimestamp >= startTime.getTime() && t.signalTimestamp <= endTime.getTime()
  );

  // Count signals, skips, errors from BotLog
  const logCounts = await prisma.botLog.groupBy({
    by: ['event'],
    where: {
      profileId,
      createdAt: { gte: startTime, lte: endTime },
    },
    _count: true,
  });

  const signalsGenerated = logCounts.find(l => l.event === 'signal')?._count ?? 0;
  const ordersPlaced = logCounts.find(l => l.event === 'order')?._count ?? 0;
  const ordersFailed = logCounts.find(l => l.event === 'error')?._count ?? 0;

  // Count skips from signal messages
  const skipLogs = await prisma.botLog.count({
    where: {
      profileId,
      event: 'signal',
      message: { contains: 'SKIP' },
      createdAt: { gte: startTime, lte: endTime },
    },
  });

  // Fee analysis
  const totalFeePaid = cycleTrades.reduce((sum, t) => sum + (t.feeCents / 100) * (t.orderSize ?? 0), 0);
  const totalRawEdge = cycleTrades.reduce((sum, t) => sum + (t.rawEdgeCents / 100) * (t.orderSize ?? 0), 0);
  const avgFeePct = cycleTrades.length > 0
    ? cycleTrades.reduce((sum, t) => sum + (t.feeCents / t.rawEdgeCents), 0) / cycleTrades.length
    : 0;

  // Best/worst trades per strategy
  const arbTrades = cycleTrades.filter(t => t.strategy === 'latency-arb');
  const sniperTrades = cycleTrades.filter(t => t.strategy === 'expiry-sniper');

  const totalTrades = arbStats.totalTrades + sniperStats.totalTrades;
  const totalPnl = arbStats.totalPnl + sniperStats.totalPnl;

  // Detect market regime from trade patterns
  const marketRegime = detectRegime(cycleTrades);

  // Generate improvements
  const improvements = analyzeAndSuggest(arbStats, sniperStats, arbBuckets, sniperBuckets, cycleTrades, totalFeePaid, totalRawEdge, balanceBefore, balanceAfter);

  const report: CycleReport = {
    cycleNumber,
    startTime: startTime.toISOString(),
    endTime: endTime.toISOString(),
    durationMinutes: Math.round(durationMinutes),

    totalTrades,
    totalPnl,
    balanceBefore,
    balanceAfter,
    roi: balanceBefore > 0 ? ((balanceAfter - balanceBefore) / balanceBefore) * 100 : 0,

    strategies: {
      'latency-arb': {
        stats: arbStats,
        confidenceBuckets: arbBuckets,
        bestTrade: findBestTrade(arbTrades),
        worstTrade: findWorstTrade(arbTrades),
      },
      'expiry-sniper': {
        stats: sniperStats,
        confidenceBuckets: sniperBuckets,
        bestTrade: findBestTrade(sniperTrades),
        worstTrade: findWorstTrade(sniperTrades),
      },
    },

    signalsGenerated,
    signalsSkipped: skipLogs,
    ordersPlaced,
    ordersFailed,

    totalFeePaid,
    avgFeePct,
    feeAsEdgePct: totalRawEdge > 0 ? (totalFeePaid / totalRawEdge) * 100 : 0,

    marketRegime,
    priceRange: [], // filled by engine from WS data

    improvements,
  };

  // Store report in BotLog
  await prisma.botLog.create({
    data: {
      profileId,
      level: 'info',
      event: 'report',
      message: `[cycle-${cycleNumber}] PnL=$${totalPnl.toFixed(2)} | ${totalTrades} trades | WR=${((arbStats.winRate + sniperStats.winRate) / 2 * 100).toFixed(0)}% | ROI=${report.roi.toFixed(2)}%`,
      data: JSON.stringify(report),
    },
  });

  return report;
}

// ─── Analysis & Suggestions ───────────────────────────

function analyzeAndSuggest(
  arbStats: TradeStats,
  sniperStats: TradeStats,
  arbBuckets: { bucket: string; trades: number; winRate: number; avgPnl: number }[],
  sniperBuckets: { bucket: string; trades: number; winRate: number; avgPnl: number }[],
  trades: TradeLogEntry[],
  totalFeePaid: number,
  totalRawEdge: number,
  balanceBefore: number,
  balanceAfter: number,
): Improvement[] {
  const improvements: Improvement[] = [];

  // 1. Overall profitability
  if (balanceAfter < balanceBefore) {
    improvements.push({
      area: 'risk',
      severity: 'critical',
      message: `Lost $${(balanceBefore - balanceAfter).toFixed(2)} this cycle. Tightening thresholds.`,
    });
  }

  // 2. Strategy-level kill switch
  for (const [name, stats] of [['latency-arb', arbStats], ['expiry-sniper', sniperStats]] as const) {
    if (stats.totalTrades >= 5 && stats.winRate < 0.35) {
      improvements.push({
        area: 'strategy',
        severity: 'critical',
        message: `${name} win rate is ${(stats.winRate * 100).toFixed(0)}% over ${stats.totalTrades} trades. Consider disabling.`,
      });
    }
    if (stats.totalTrades >= 5 && stats.totalPnl < 0 && stats.profitFactor < 0.5) {
      improvements.push({
        area: 'strategy',
        severity: 'critical',
        message: `${name} profit factor ${stats.profitFactor.toFixed(2)} — losing 2x what it wins. Disable or increase min edge.`,
        suggestion: { param: 'minEdgeCents', from: 1.5, to: 3.0 },
      });
    }
  }

  // 3. Confidence calibration — check if low-confidence trades are losing
  for (const [name, buckets] of [['latency-arb', arbBuckets], ['expiry-sniper', sniperBuckets]] as const) {
    for (const b of buckets) {
      if (b.trades >= 3 && b.winRate < 0.4 && b.avgPnl < 0) {
        const minConf = parseInt(b.bucket.split('-')[1]);
        improvements.push({
          area: 'confidence',
          severity: 'warning',
          message: `${name} confidence ${b.bucket} has ${(b.winRate * 100).toFixed(0)}% WR. Raise min confidence above ${minConf}.`,
          suggestion: { param: 'minConfidence', from: parseInt(b.bucket.split('-')[0]), to: minConf },
        });
      }
    }
  }

  // 4. Fee drag analysis
  if (totalRawEdge > 0 && totalFeePaid / totalRawEdge > 0.5) {
    improvements.push({
      area: 'fees',
      severity: 'warning',
      message: `Fees ate ${((totalFeePaid / totalRawEdge) * 100).toFixed(0)}% of raw edge. Switch to post-only (maker) orders.`,
      suggestion: { param: 'preferMaker', from: 0, to: 1 },
    });
  }

  // 5. Trades near 50c losing more
  const midPriceTrades = trades.filter(t => t.yesTokenPrice > 0.35 && t.yesTokenPrice < 0.65);
  if (midPriceTrades.length >= 3) {
    const midPnl = midPriceTrades.reduce((sum, t) => sum + (t.pnl ?? 0), 0);
    if (midPnl < 0) {
      improvements.push({
        area: 'fees',
        severity: 'warning',
        message: `${midPriceTrades.length} trades in 35-65c zone lost $${Math.abs(midPnl).toFixed(2)}. Fee curve kills edge here.`,
      });
    }
  }

  // 6. Sizing — check if we're risking too much on losers
  const bigLosses = trades.filter(t => (t.pnl ?? 0) < -5);
  if (bigLosses.length > 0) {
    const avgLossSize = bigLosses.reduce((sum, t) => sum + t.orderSize, 0) / bigLosses.length;
    improvements.push({
      area: 'sizing',
      severity: 'warning',
      message: `${bigLosses.length} large losses (>$5). Avg size: ${avgLossSize.toFixed(1)} shares. Reduce Kelly fraction.`,
      suggestion: { param: 'kellyFraction', from: 0.25, to: 0.15 },
    });
  }

  // 7. No trades at all
  if (trades.length === 0) {
    improvements.push({
      area: 'confidence',
      severity: 'info',
      message: 'No trades this cycle. Thresholds may be too tight, or no markets available.',
      suggestion: { param: 'minConfidence', from: 55, to: 45 },
    });
  }

  // 8. Timing analysis for expiry sniper
  const sniperTrades = trades.filter(t => t.strategy === 'expiry-sniper' && t.secondsToExpiry);
  if (sniperTrades.length >= 3) {
    const earlyEntries = sniperTrades.filter(t => (t.secondsToExpiry ?? 0) > 60);
    const lateEntries = sniperTrades.filter(t => (t.secondsToExpiry ?? 0) <= 30);
    const earlyPnl = earlyEntries.reduce((sum, t) => sum + (t.pnl ?? 0), 0);
    const latePnl = lateEntries.reduce((sum, t) => sum + (t.pnl ?? 0), 0);

    if (earlyEntries.length >= 2 && earlyPnl < 0 && latePnl >= 0) {
      improvements.push({
        area: 'timing',
        severity: 'warning',
        message: `Early sniper entries (>60s) lost $${Math.abs(earlyPnl).toFixed(2)}, late entries (<30s) made $${latePnl.toFixed(2)}. Reduce entry window.`,
      });
    }
  }

  return improvements;
}

// ─── Helpers ───────────────────────────────────────────

function detectRegime(trades: TradeLogEntry[]): 'trending' | 'sideways' | 'volatile' | 'unknown' {
  if (trades.length < 3) return 'unknown';

  const momentums = trades
    .filter(t => t.microMomentum !== undefined)
    .map(t => t.microMomentum!);

  if (momentums.length < 3) return 'unknown';

  const avgMomentum = momentums.reduce((a, b) => a + b, 0) / momentums.length;
  const absAvg = Math.abs(avgMomentum);
  const volatility = Math.sqrt(
    momentums.reduce((sum, m) => sum + (m - avgMomentum) ** 2, 0) / momentums.length
  );

  if (absAvg > 0.001) return 'trending';
  if (volatility > 0.002) return 'volatile';
  return 'sideways';
}

function findBestTrade(trades: TradeLogEntry[]): TradeSummary | null {
  if (trades.length === 0) return null;
  const best = trades.reduce((a, b) => ((a.pnl ?? -Infinity) > (b.pnl ?? -Infinity) ? a : b));
  return {
    conditionId: best.conditionId,
    direction: best.direction,
    entryPrice: best.orderPrice,
    pnl: best.pnl ?? 0,
    confidence: best.confidence,
    edge: best.netEdgeCents,
  };
}

function findWorstTrade(trades: TradeLogEntry[]): TradeSummary | null {
  if (trades.length === 0) return null;
  const worst = trades.reduce((a, b) => ((a.pnl ?? Infinity) < (b.pnl ?? Infinity) ? a : b));
  return {
    conditionId: worst.conditionId,
    direction: worst.direction,
    entryPrice: worst.orderPrice,
    pnl: worst.pnl ?? 0,
    confidence: worst.confidence,
    edge: worst.netEdgeCents,
  };
}

// ─── Report Formatting ────────────────────────────────

export function formatReportText(report: CycleReport): string {
  const lines: string[] = [];
  const hr = '─'.repeat(50);

  lines.push(hr);
  lines.push(`CYCLE #${report.cycleNumber} REPORT`);
  lines.push(`${report.startTime} → ${report.endTime} (${report.durationMinutes}min)`);
  lines.push(hr);

  lines.push('');
  lines.push('## P&L Summary');
  lines.push(`  Balance: $${report.balanceBefore.toFixed(2)} → $${report.balanceAfter.toFixed(2)} (${report.roi >= 0 ? '+' : ''}${report.roi.toFixed(2)}%)`);
  lines.push(`  Total PnL: $${report.totalPnl.toFixed(2)}`);
  lines.push(`  Trades: ${report.totalTrades} | Signals: ${report.signalsGenerated} | Skipped: ${report.signalsSkipped}`);

  for (const [name, strat] of Object.entries(report.strategies)) {
    lines.push('');
    lines.push(`## ${name}`);
    lines.push(`  Trades: ${strat.stats.totalTrades} | Win: ${strat.stats.wins} | Loss: ${strat.stats.losses}`);
    lines.push(`  Win Rate: ${(strat.stats.winRate * 100).toFixed(1)}% | PF: ${strat.stats.profitFactor === Infinity ? '∞' : strat.stats.profitFactor.toFixed(2)}`);
    lines.push(`  PnL: $${strat.stats.totalPnl.toFixed(2)} | Avg: $${strat.stats.avgPnl.toFixed(2)}`);
    lines.push(`  Avg Edge: ${strat.stats.avgEdgeCents.toFixed(1)}c | Avg Conf: ${strat.stats.avgConfidence.toFixed(0)}`);

    if (strat.bestTrade) {
      lines.push(`  Best: $${strat.bestTrade.pnl.toFixed(2)} (conf=${strat.bestTrade.confidence})`);
    }
    if (strat.worstTrade) {
      lines.push(`  Worst: $${strat.worstTrade.pnl.toFixed(2)} (conf=${strat.worstTrade.confidence})`);
    }
  }

  lines.push('');
  lines.push('## Fee Analysis');
  lines.push(`  Total Fees: $${report.totalFeePaid.toFixed(2)}`);
  lines.push(`  Fee as % of Edge: ${report.feeAsEdgePct.toFixed(1)}%`);
  lines.push(`  Market Regime: ${report.marketRegime}`);

  if (report.improvements.length > 0) {
    lines.push('');
    lines.push('## Improvements');
    for (const imp of report.improvements) {
      const icon = imp.severity === 'critical' ? '[!!]' : imp.severity === 'warning' ? '[!]' : '[i]';
      lines.push(`  ${icon} [${imp.area}] ${imp.message}`);
      if (imp.suggestion) {
        lines.push(`      → ${imp.suggestion.param}: ${imp.suggestion.from} → ${imp.suggestion.to}`);
      }
    }
  }

  lines.push(hr);
  return lines.join('\n');
}
